### ISSUE TITLE
Using pre-trained models on R10.3 Reads 

### ISSUE THREAD

**Issue by jcolicchio-soundag** [TheLuoFengLab/deepsignal-plant#1]
I was wondering what your thoughts are on the ability to use your pretrained models to call methylation on reads sequenced using the new 10.3 flow cells?  I gave it a quick test and the results seemed reasonable, but I wasn't sure if perhaps it makes more sense to us 9.4 flow cells for now since that is what the models were trained on.

**Comment by PengNi** [comment]
@jcolicchio-soundag , thanks for your interest of deepsignal-plant. We didn't evaluate our tool on R10.3 flow cells, since we don't have R10.3 data in our hands. So my thoughts are that the results of R10.3 flow cells cannot be guaranteed for now, unless the results are validated by a comparison with R9.4 data or BS-seq data. We hope that we can train a new R10.3 model in the future too.

Best,
Peng
